{% set version = "0.6.2" %}
{% set sha256 = "caac5966fb57268bf6b9239af9dd26e6b78ebc3f1e3845b68866d41308a2c2ee" %}

package:
  name: jupyter_cms
  version: {{ version }}

source:
  fn: jupyter_cms-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyter_cms/jupyter_cms-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - jupyter-cms = jupyter_cms.extensionapp:main
    - jupyter-bundler = jupyter_cms.bundlerapp:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - notebook >=4.0.0
    - ipython >=4.1.0
    - whoosh >=2.7.0
    - scandir >=1.1  # [py27 or py34]

test:
  imports:
    - jupyter_cms 
  commands:
    - jupyter-cms --help
    - jupyter cms --help

about:
  home: http://github.com/jupyter-incubator/contentmanagement
  license: BSD 3-Clause
  license_file: LICENSE.md
  summary: Jupyter Notebook Content Management Extensions
  dev_url: https://github.com/jupyter-incubator/contentmanagement

extra:
  recipe-maintainers:
    - parente
