# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "PRv93gfkmH9fwzXuo88OMJ65RDVekOvq7o4kcynumpNHAtqbqehoKXPlKxBSAisdOuvHtK9JD2ihZFCCxViMSyeaggzfIFilx6evHY3ARVfLl0gHOA90BmgdvTEljgf5vQS3STs3j0fYSKhs5DXK8URTpdJVRXonlhqw4Gi+EqqI+vtNp5bA2/eLlDCUPEiPc+yjVw0j5+hky3ijfRKOl+FjoPHpEf1l/BpXdZD67ahbickOWNaJzqbwn4+bZfK22WRT5ob4iD76uXqAH0sUyK7PgVNvUEC79/8bdaXM+lGNxGa9SOONHy6HfRnT/ZmTsMhUcH5f1YRQfGjr9iY1Z4mQALVs7AXLnhaUdZYPrlsVrV2820OTmp5/nkTz4bpm+xnsMks50b11ob5U/UlCB0kBpkFuwN/oFtOZAWILf0X8Wls7boQq/R7eah5tAGXVgv3SVYq9WVlnh+6OCF4wdd1Wsx2yuf8c9mCPL6pYnEYXlt/cFqOaL4U6EmJ4HMAwdBr2ZmuBppwdsb1Hg2TmDEYUPiJL18a+3JMGuggDghcuyjeaBpM0yeRUjCUJ/blm6ftMZ95hA0JIV8HTfbA84h4xl2EfMtZbsOGjTqQHK7tM3OlSkdbQ551zGuhx7jTzUfaFTNrUZffp1PNo6tv8XyUuHQjLhRdqRR0WN+LFL8k="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
