travis:
  secure:
    BINSTAR_TOKEN: PRv93gfkmH9fwzXuo88OMJ65RDVekOvq7o4kcynumpNHAtqbqehoKXPlKxBSAisdOuvHtK9JD2ihZFCCxViMSyeaggzfIFilx6evHY3ARVfLl0gHOA90BmgdvTEljgf5vQS3STs3j0fYSKhs5DXK8URTpdJVRXonlhqw4Gi+EqqI+vtNp5bA2/eLlDCUPEiPc+yjVw0j5+hky3ijfRKOl+FjoPHpEf1l/BpXdZD67ahbickOWNaJzqbwn4+bZfK22WRT5ob4iD76uXqAH0sUyK7PgVNvUEC79/8bdaXM+lGNxGa9SOONHy6HfRnT/ZmTsMhUcH5f1YRQfGjr9iY1Z4mQALVs7AXLnhaUdZYPrlsVrV2820OTmp5/nkTz4bpm+xnsMks50b11ob5U/UlCB0kBpkFuwN/oFtOZAWILf0X8Wls7boQq/R7eah5tAGXVgv3SVYq9WVlnh+6OCF4wdd1Wsx2yuf8c9mCPL6pYnEYXlt/cFqOaL4U6EmJ4HMAwdBr2ZmuBppwdsb1Hg2TmDEYUPiJL18a+3JMGuggDghcuyjeaBpM0yeRUjCUJ/blm6ftMZ95hA0JIV8HTfbA84h4xl2EfMtZbsOGjTqQHK7tM3OlSkdbQ551zGuhx7jTzUfaFTNrUZffp1PNo6tv8XyUuHQjLhRdqRR0WN+LFL8k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
